default: bwtdecode bwtsearch

bwtdecode: bwtdecode.c helper.h
	gcc -O3 -g -Wall -Werror bwtdecode.c helper.h -o bwtdecode   
bwtsearch: bwtsearch.c helper2.h
	gcc -O3 -Wall -Werror bwtsearch.c helper2.h -o bwtsearch
 	
 	

