default: bwtdecode bwtsearch

bwtdecode: bwtdecode.c helper.h
	gcc -O3 -Wall -Werror bwtdecode.c helper.h -o bwtdecode   
bwtsearch: bwtsearch.cpp
	g++ -Wall -Werror -O3 -o bwtsearch bwtsearch.cpp  
 	
 	

